#!/bin/bash
set -e

cd $(dirname $0)

test nginx-start.go -nt nginx-start && GOOS=linux GOARCH=amd64 go build nginx-start.go

name=registry.cn-beijing.aliyuncs.com/lovego/nginx:2

docker build --pull -t $name .

if test "$1" = '-p'; then
  docker push $name
fi
