#!/bin/bash
set -e

cd $(dirname $0)

if [[ $(file -b xiaomei) != 'ELF '* ]]; then
  GOOS=linux GOARCH=amd64 go build -v -o xiaomei ../../..
fi

if [[ $(file -b gospec) != 'ELF '* ]]; then
                          go get   -v -d        github.com/lovego/gospec
  GOOS=linux GOARCH=amd64 go build -v -o gospec github.com/lovego/gospec
fi

name=registry.cn-beijing.aliyuncs.com/lovego/xiaomei

docker build -t $name .

if test "$1" = '-p'; then
  docker push $name
fi
