#!/bin/bash
set -e

cd $(dirname $0)

sudo GOOS=linux GOARCH=amd64 go build -i -v -o xiaomei github.com/lovego/xiaomei
sudo GOOS=linux GOARCH=amd64 go build -i -v -o gospec github.com/lovego/gospec

name=registry.cn-beijing.aliyuncs.com/lovego/xiaomei

docker build -t $name .

if test "$1" = '-p'; then
  docker push $name
fi
