#!/bin/bash
set -e

cd $(dirname $0)

test nginx/nginx-start.go -nt nginx/nginx-start &&
    GOOS=linux GOARCH=amd64 go build -v -o nginx/nginx-start nginx/nginx-start.go

test logc/docker-kill.go  -nt logc/docker-kill &&
    GOOS=linux GOARCH=amd64 go build -v -o logc/docker-kill docker-kill.go

if [[ $(file -b logc/logc) != 'ELF '* ]]; then
                            go get   -v -d           github.com/lovego/logc@latest
    GOOS=linux GOARCH=amd64 go build -v -o logc/logc github.com/lovego/logc
fi

name=registry.cn-beijing.aliyuncs.com/lovego/service

docker build -t $name .

if test "$1" = '-p'; then
  docker push $name
fi
