#!/bin/bash
set -e

cd $(dirname $0)

test docker-kill.go -nt docker-kill && GOOS=linux GOARCH=amd64 go build -v docker-kill.go

name=hub.c.163.com/lovego/xiaomei/logc:2

docker build --pull -t $name .

if test "$1" = '-p'; then
  docker push $name
fi
